extends RefCounted

func run(t) -> void:
	# list labels
	t.check_eq(CodexText.list_label(true, "Mire Wolf"), "Mire Wolf", "discovered label is the name")
	t.check_eq(CodexText.list_label(false, "Mire Wolf"), "???", "undiscovered label is hidden")

	# tab titles
	t.check_eq(CodexText.tab_title("Bestiary", 5, 12), "Bestiary 5/12", "tab title")

	# enemies
	var not_met := CodexText.enemy_entry("mire_wolf", false, 0, false)
	t.check(not_met.contains("Not yet discovered"), "unmet enemy is undiscovered")
	t.check(not not_met.contains("Mire Wolf"), "unmet enemy does not reveal its name")
	t.check(not not_met.contains("Mirewater"), "no zone hint before the zone is visited")
	var hinted := CodexText.enemy_entry("mire_wolf", false, 0, true)
	t.check(hinted.contains("Lurks somewhere in Mirewater Swamp"), "zone hint once visited")
	t.check(not hinted.contains("Mire Wolf"), "the hint still hides the name")
	var met := CodexText.enemy_entry("mire_wolf", true, 0, true)
	t.check(met.contains("Mire Wolf"), "met enemy shows its name")
	t.check(met.contains("HP: 45"), "met enemy shows hp")
	t.check(met.contains("Damage: 5 - 9"), "met enemy shows damage")
	t.check(met.contains("Mirewater Swamp"), "met enemy shows its zone")
	t.check(not met.contains("XP"), "xp is hidden until the first kill")
	var killed := CodexText.enemy_entry("mire_wolf", true, 3, true)
	t.check(killed.contains("XP: 55"), "xp shown after a kill")
	t.check(killed.contains("Gold: 3 - 6"), "gold range shown after a kill")
	t.check(killed.contains("Kills: 3"), "kill count shown")
	t.check(killed.contains("Drops:"), "drops shown after a kill")
	var boss := CodexText.enemy_entry("mire_tyrant", true, 1, true)
	t.check(boss.contains("Boss"), "guaranteed-drop enemies are tagged")
	var maul_hex: String = LootTable.RARITY_COLORS["epic"].to_html(false)
	t.check(boss.contains("[color=#%s]Tyrants Maul[/color]" % maul_hex), "the guaranteed drop is shown in its rarity color")
	t.check_eq(CodexText.enemy_entry("no_such_enemy", true, 1, true), "", "unknown enemy has no entry")

	# items
	var unfound := CodexText.item_entry("iron_sword", false)
	t.check(unfound.contains("Not yet discovered"), "unfound item is undiscovered")
	t.check(not unfound.contains("Iron Sword"), "unfound item hides its name")
	t.check(unfound.contains("Weapon"), "unfound item hints its slot")
	var found := CodexText.item_entry("iron_sword", true)
	var uncommon_hex: String = LootTable.RARITY_COLORS["uncommon"].to_html(false)
	t.check(found.contains("[color=#%s]Iron Sword[/color]" % uncommon_hex), "found item is rarity-colored")
	t.check(found.contains("+7 damage"), "stat line")
	t.check(found.contains("Level 1"), "level requirement")
	t.check(found.contains("Guaranteed drop: Bandit Captain"), "guaranteed source")
	t.check(found.contains("Quest reward: The Captain's Head"), "quest source")
	var random_item := CodexText.item_entry("rusty_sword", true)
	t.check(random_item.contains("Random drops from level 2 enemies"), "random source line")
	var potion := CodexText.item_entry("health_potion", true)
	t.check(potion.contains("Heals 20 HP"), "consumables show their heal")
	var epic := CodexText.item_entry("tyrants_maul", true)
	t.check(not epic.contains("Random drops"), "epics have no random source line")
	t.check_eq(CodexText.item_entry("no_such_item", true), "", "unknown item has no entry")

	# zones
	var unvisited := CodexText.zone_entry("mirewater_swamp", false, [])
	t.check(unvisited.contains("Not yet discovered"), "unvisited zone is undiscovered")
	t.check(not unvisited.contains("Mirewater"), "unvisited zone hides its name")
	var visited := CodexText.zone_entry("mirewater_swamp", true, ["mire_wolf"])
	t.check(visited.contains("Mirewater Swamp"), "visited zone shows its name")
	t.check(visited.contains("Levels 4"), "level range shown")
	t.check(visited.contains("Mire Wolf"), "met enemies are listed by name")
	t.check(visited.contains("???"), "unmet enemies are hidden")
	t.check(not visited.contains("Bog Bandit"), "unmet enemies are not named")
	t.check(visited.contains("Discovered: 1/3"), "discovered count")
	var boss_met := CodexText.zone_entry("mirewater_swamp", true, ["mire_tyrant"])
	t.check(boss_met.contains("Boss: Mire Tyrant"), "the boss is named once met")
	var boss_hidden := CodexText.zone_entry("mirewater_swamp", true, [])
	t.check(boss_hidden.contains("Boss: ???"), "the boss is hidden until met")
	var no_boss := CodexText.zone_entry("thornfield_meadow", true, [])
	t.check(not no_boss.contains("Boss:"), "zones without a boss have no boss line")
	t.check_eq(CodexText.zone_entry("no_such_zone", true, []), "", "unknown zone has no entry")
	t.done()
